packaging_format = 2

id = "joomla"
name = "Joomla"
description.en = "Content management system"
description.fr = "Système de gestion de contenu libre"

version = "5.0.0~ynh1"

maintainers = ["Anmol Sharma"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.joomla.org/"
admindoc = "https://docs.joomla.org/"
code = "https://github.com/joomla/joomla-cms"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/joomla"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Password must be longer than 8 characters."
    help.fr = "Le mot de passe doit comporter plus de 8 caractères."
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/joomla/joomla-cms/releases/download/5.0.0/Joomla_5.0.0-Stable-Full_Package.tar.gz"
        sha256 = "db192b707da759f245c53318bb29a3cac87cd2012d39d6359456266304bbb2e4"
        in_subdir = false
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-xml, php8.2-cli, php8.2-posix, php8.2-bz2, php8.2-zip, php8.2-memcache, php8.2-memcached, php8.2-ldap, php8.2-curl, php8.2-sockets, php8.2-mcrypt, php8.2-mysql, php8.2-mysqli, php8.2-gd, php8.2-fileinfo, php8.2-mbstring"

    [resources.database]
    type = "mysql"
