packaging_format = 2

id = "joomla"
name = "Joomla"
description.en = "Content management system"
description.fr = "Système de gestion de contenu libre"

version = "5.1.4~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "https://www.joomla.org/"
admindoc = "https://docs.joomla.org/"
code = "https://github.com/joomla/joomla-cms"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/joomla"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Password must be longer than 8 characters."
    help.fr = "Le mot de passe doit comporter plus de 8 caractères."
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/joomla/joomla-cms/releases/download/5.1.4/Joomla_5.1.4-Stable-Full_Package.tar.gz"
        sha256 = "1833f048afdbf2fa6fcd61fd08ee385239624798c8ecd2f7f6038a8fbd70e443"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^Joomla_.*-Stable-Full_Package.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.1-xml, php8.1-cli, php8.1-posix, php8.1-bz2, php8.1-zip, php8.1-memcache, php8.1-memcached, php8.1-ldap, php8.1-curl, php8.1-sockets, php8.1-mcrypt, php8.1-mysql, php8.1-gd, php8.1-fileinfo, php8.1-mbstring"

    [resources.database]
    type = "mysql"
