packaging_format = 2

id = "joomla"
name = "Joomla"
description.en = "Content management system"
description.fr = "Système de gestion de contenu libre"

version = "5.2.3~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0-only"
website = "https://www.joomla.org/"
admindoc = "https://docs.joomla.org/"
code = "https://github.com/joomla/joomla-cms"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/joomla"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Password must be longer than 8 characters."
    help.fr = "Le mot de passe doit comporter plus de 8 caractères."
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/joomla/joomla-cms/releases/download/5.2.3/Joomla_5.2.3-Stable-Full_Package.tar.gz"
        sha256 = "8fca93a0f3f1a8bbb1464bc276aad524d0cedf8d4f5437b1fd587df995791c00"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^Joomla_.*-Stable-Full_Package.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.3-xml, php8.3-cli, php8.3-posix, php8.3-bz2, php8.3-zip, php8.3-memcache, php8.3-memcached, php8.3-ldap, php8.3-curl, php8.3-sockets, php8.3-mcrypt, php8.3-mysql, php8.3-gd, php8.3-fileinfo, php8.3-mbstring"

    [resources.database]
    type = "mysql"
