test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    # very old version 
   # test_upgrade_from.08222d1d.name = "Upgrade from 4.2.6"
