#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove the log files
#REMOVEME? (Apps should not remove their log dir during remove ... this should only happen if --purge is used, and be handled by the core...) ynh_safe_rm "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
